#!/bin/bash

#COLORS
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
BLUE='\033[0;34m'
patch=1.0
#END COLORS

front(){
printf "${BLUE}
   ______________   _______  __
   __  ____/___  | / /__  / / /
   _  /     __   |/ / _  / / / 
   / /___   _  /|  /  / /_/ /  
   \____/   /_/ |_/   \____/   
                            
__________________________ _________
__  ____/__  ____/___  __ \__  ____/
_  /     _  /     __  / / /_  /     
/ /___   / /___   _  /_/ / / /___   
\____/   \____/   /_____/  \____/ 
              
              v${patch}
              
   <@TODO: MENU HERE WITH OPTIONS>           
              
CNU CCDC ${NC}|${BLUE} root💀kali ---> "
read choice
}
front


