#!/bin/bash

#COLORS
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
BLUE='\033[0;34m'
patch=1.0
#END COLORS
#FUNCTIONS START----------------------------------------------------------------------------------------------------------------------------------------------------
nmapipscan(){

printf "${YLLW} [+] Please enter your target IP address ---> "
read targip
echo '[+] What ports would you like to scan on --->'
echo '[*] Starting Port ---> '
read startport
echo '[*] End Port ---> '
read endport
gnome-terminal --command="bash -c 'nmap -T4 -A -sC -vv -p$startport-$endport $targip; $SHELL'"
}
niktowebscan(){

printf  "${YLLW}[+] Enter the URL you would like to scan ---> "
read url
gnome-terminal --command="bash -c 'nikto -h $url; $SHELL'"
clear
printf "${GREEN}
-------------------------------------
[✓] FINISHED SCANNING		 [✓] |
-------------------------------------"
}
updater(){
printf "Enter your github email: "
read email
printf "Enter your github username: "
read username
git config --global user.email "$email"
git config --global user.name "$username"
clear
git pull
printf "${GREEN}
-------------------------------------
[✓] FINISHED UPDATING		 [✓] |
-------------------------------------" 
sleep 3
front
}
#MENUS UNDER THIS COMMENT-------------------------------------------------------------------------------------------------------------------------------------------
front(){
printf "${BLUE}
   			     ______________   _______  __
   			     __  ____/___  | / /__  / / /
   		 	     _  /     __   |/ / _  / / / 
   			     / /___   _  /|  /  / /_/ /  
   			     \____/   /_/ |_/   \____/   
                            
			__________________________ _________
			__  ____/__  ____/___  __ \__  ____/
			_  /     _  /     __  / / /_  /     
			/ /___   / /___   _  /_/ / / /___   
			\____/   \____/   /_____/  \____/ 
              
              			     v${patch}
              
   		             Always one step ahead. 
   	
-------------------------------------------------------------------------------
                 	           Main Menu                                   |                                                
-------------------------------------------------------------------------------
1) Attack Vector Scanning              |                                       |
                                       |                                       |
	                               |				       |
	                               |                                       |
   				       |                                       |
    				       |                                       |
                                       |                                       |
5) Check for client Update             |                                       |
                                       |                                       |                
         MORE SOON!  	               |            MORE SOON!                 |                
                                       |                                       |                
-------------------------------------------------------------------------------         
              
CNU CCDC ${NC}|${BLUE} root💀kali ---> "
read choice
if [ $choice == '1' ]
then
	clear
	scanmenu
	
elif [ $choice == '5' ]
then
	clear
	updater
	
	
else
	echo 'Invalid Menu Selection'
	front
fi

}
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------
scanmenu(){
printf "
-------------------------------------------------------------------------------
                 	     Attack Vector Scanning                            |                                                
-------------------------------------------------------------------------------
1) NMAP Scan  (NMAP)                   |                                       |
2) Nikto Web Scan (Nikto)              |                                       |
	                               |				       |
	                               |                                       |
   				       |                                       |
    				       |                                       |
                                       |                                       |
                                       |                                       |
                                       |                                       |                
         MORE SOON!  	               |            MORE SOON!                 |                
                                       |                                       |                
-------------------------------------------------------------------------------         
              
CNU CCDC ${NC}|${BLUE} root💀kali ---> "
read choice
if [ $choice == '1' ]
then

	nmapipscan
	
elif [ $choice == '2' ]
then

	niktowebscan

else
	echo 'Invlaid Selection'
	clear
	scanmenu
fi
}
#END OF FUCNTION DEVELOPMENT -----------------------------------------------------------------------------------------------------------------------------------------
front

























